-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 12:53:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `serial_no` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `autotrans` VARCHAR(45) NOT NULL,
  `warehouse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`serial_no`),
  UNIQUE INDEX `serial_no_UNIQUE` (`serial_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Representative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Representative` (
  `rep_no` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `base_salary` DECIMAL(100) NOT NULL,
  `ytd_sales` DECIMAL(100) NOT NULL,
  `comm` DECIMAL(100) NOT NULL,
  PRIMARY KEY (`rep_no`),
  UNIQUE INDEX `rep_no_UNIQUE` (`rep_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_D1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_D1` (
  `customer_no` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_no`),
  UNIQUE INDEX `customer_no_UNIQUE` (`customer_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `loan_no` INT NOT NULL,
  `amount` DECIMAL(100) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  PRIMARY KEY (`loan_no`),
  UNIQUE INDEX `loan_no_UNIQUE` (`loan_no` ASC),
  CONSTRAINT `customer_no`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Customer_D1` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rebate1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rebate1` (
  `rebate_no` INT NOT NULL,
  `amount` DECIMAL(100) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  PRIMARY KEY (`rebate_no`),
  UNIQUE INDEX `rebate_no_UNIQUE` (`rebate_no` ASC),
  CONSTRAINT `serial_no`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Car` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `transaction_no` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(100) NOT NULL,
  `rebate` DECIMAL(100) NOT NULL,
  `final_amount` DECIMAL(100) NOT NULL,
  PRIMARY KEY (`transaction_no`),
  UNIQUE INDEX `transaction_no_UNIQUE` (`transaction_no` ASC),
  CONSTRAINT `rep_no`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Representative` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_no`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Customer_D1` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serial_no`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Car` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
